options=optimset('Display','final',...
                 'LargeScale','on', ...
                 'TolX',1e-4,...
                 'TolFun',1e-4,...
                 'DerivativeCheck','off',...
                 'Diagnostics','off',...
                 'Jacobian','off',...
                 'JacobMult',[],... % JacobMult set to [] by default
                 'JacobPattern','sparse(ones(Jrows,Jcols))',...
                 'MaxFunEvals','100*numberOfVariables',...
                 'DiffMaxChange',1e-1,...
                 'DiffMinChange',1e-8,...
                 'PrecondBandWidth',0,...
                 'TypicalX','ones(numberOfVariables,1)',...
                 'MaxPCGIter','max(1,floor(numberOfVariables/2))', ...
                 'TolPCG',0.1,...
                 'MaxIter',10000,...
                 'LineSearchType','quadcubic',...
                 'LevenbergMarquardt','on'); 

if (exist('c') & exist('d') & exist('e'))==0
    c=1;
    d=0;
    e=0;
end
int_par=[c,d,e,xc,yc];

[ssout,resnorm,residual,exitflag,output] =lsqnonlin(@prova2,int_par,-inf,inf,options,ss,RRfin, ima_proc,Xp_abs,Yp_abs,M, width, height);
fprintf(1,'Camera model optimized');


c=ssout(1)
d=ssout(2)
e=ssout(3)
xc=ssout(4)
yc=ssout(5)

ocam_model.ss=ss;
ocam_model.xc=xc;
ocam_model.yc=yc;
ocam_model.c=c;
ocam_model.d=d;
ocam_model.e=e;
ocam_model.width=width;
ocam_model.height=height;
reprojectpoints_adv(ocam_model, RRfin, ima_proc, Xp_abs, Yp_abs, M);
ss


